### ISSUE TITLE
huangyaowei's comment

### ISSUE THREAD

**Issue by HuangYaowei** [CurryTXL/Guessing-numbers#2]
1. don't define 'i' in a for statement,like the one in  the 29th sentence.
   2.The  function and style are pretty good ,so I think you could think more.Like you could limit people to input the number only between 0 and 9,if a user input 11,you could tell him it's wrong.
   3.And in the 56th sentence,you could write while function under},in 57th sentence.

**Comment by CurryTXL** [comment]
Thank you for your suggestion.
